---
fabric_name: AVD_FABRIC

service_routing_protocols_model: multi-agent

custom_structured_configuration_prefix:
  - custom_structured_configuration_
  - custom_spines_
  - custom_mpls_

custom_structured_configuration_spanning_tree:
  mode: mstp

ip_routing: true

# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: Management1
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.0.1
mgmt_vrf_routing: true

node_type_keys:

  - key: spine
    

